pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('a930af01-7285-420d-b3b5-66a9b5dd7752')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    stages {
        stage('Clone github repository') {
            steps {
                cleanWs()
                sh '''
                    git clone -b main https://github.com/Alex-Andrv/mle-lab1.git
                '''
            }
        }

        stage('Checkout repo dir') {
            steps {
                sh '''
                    cd mle-lab1
                    ls -la
                '''
            }
        }

        stage('Login') {
            steps {
                sh '''
                    echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin
                '''
            }
        }

        stage('Create and run docker container') {
            steps {
                script {
                    try {
                        sh '''
                            cd mle-template
                            docker-compose build
                        '''
                    } finally {
                        sh '''
                            cd mle-template
                            docker-compose up -d
                        '''
                    }
                }
            }
        }

        stage('Checkout container logs') {
            steps {
                dir("mle-template") {
                    sh '''
                        docker-compose up -d
                        containerId=$(docker ps -qf "name=mle-template-web-1")
                        echo $containerId
                        if [ -z "$containerId" ]; then
                            echo "No container running"
                        else
                            docker logs --tail 1000 -f $containerId
                        fi
                    '''
                }
            }
        }

        stage('Checkout coverage report') {
            steps {
                dir("mle-template") {
                    sh '''
                        docker-compose logs -t --tail 10
                    '''
                }
            }
        }

        stage('Push') {
            steps {
                sh '''
                    docker push sesh31/mle-lab2:latest
                '''
            }
        }
    }

    post {
        always {
            sh '''
                docker logout
            '''
        }
    }
}
